export const changedDataReport = [
  {
    period: 'harian',
    data: [
      {
        komoditi: 'Beras Medium SPHP Thailand',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 80,
        stok_masuk: 5,
        stok_keluar: 0,
        stok_akhir: 85,
        keterangan: 'Penambahan stok dari hasil GPM',
      },
      {
        komoditi: 'Beras Medium SPHP Thailand',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 85,
        stok_masuk: 0,
        stok_keluar: 5,
        stok_akhir: 80,
        keterangan: 'Pengurangan stok karena barang rusak',
      },
      {
        komoditi: 'Beras Medium SPHP Vietnam',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 100,
        stok_masuk: 0,
        stok_keluar: 10,
        stok_akhir: 90,
        keterangan: 'Stok dikurang karena diambil pak Wanto',
      },
    ],
  },
  {
    period: 'mingguan',
    data: [
      {
        komoditi: 'Gula Manis Kita',
        divisi: 'Komersil',
        stok_awal: 50,
        stok_masuk: 0,
        stok_keluar: 10,
        stok_akhir: 40,
        keterangan: 'Stok dikurang karena dipakai untuk paketan',
      },
      {
        komoditi: 'Beras Medium SPHP Thailand',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 80,
        stok_masuk: 5,
        stok_keluar: 0,
        stok_akhir: 85,
        keterangan: 'Penambahan stok dari hasil GPM',
      },
      {
        komoditi: 'Beras Medium SPHP Thailand',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 85,
        stok_masuk: 0,
        stok_keluar: 5,
        stok_akhir: 80,
        keterangan: 'Pengurangan stok karena barang rusak',
      },
      {
        komoditi: 'Beras Medium SPHP Vietnam',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 100,
        stok_masuk: 0,
        stok_keluar: 10,
        stok_akhir: 90,
        keterangan: 'Stok dikurang karena diambil pak Wanto',
      },
    ],
  },
  {
    period: 'bulanan',
    data: [
      {
        komoditi: 'Beras Premium Slyp Super',
        divisi: 'Komersil',
        stok_awal: 40,
        stok_masuk: 20,
        stok_keluar: 0,
        stok_akhir: 60,
        keterangan: 'Penambahan stok dari hasil GPM Kereng Bangkirai',
      },
      {
        komoditi: 'Gula Manis Kita',
        divisi: 'Komersil',
        stok_awal: 50,
        stok_masuk: 0,
        stok_keluar: 10,
        stok_akhir: 40,
        keterangan: 'Stok dikurang karena dipakai untuk paketan',
      },
      {
        komoditi: 'Beras Medium SPHP Thailand',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 80,
        stok_masuk: 5,
        stok_keluar: 0,
        stok_akhir: 85,
        keterangan: 'Penambahan stok dari hasil GPM',
      },
      {
        komoditi: 'Beras Medium SPHP Thailand',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 85,
        stok_masuk: 0,
        stok_keluar: 5,
        stok_akhir: 80,
        keterangan: 'Pengurangan stok karena barang rusak',
      },
      {
        komoditi: 'Beras Medium SPHP Vietnam',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 100,
        stok_masuk: 0,
        stok_keluar: 10,
        stok_akhir: 90,
        keterangan: 'Stok dikurang karena diambil pak Wanto',
      },
    ],
  },
  {
    period: 'tahunan',
    data: [
      {
        komoditi: 'Minyak Goreng Kita',
        divisi: 'Komersil',
        stok_awal: 100,
        stok_masuk: 10,
        stok_keluar: 0,
        stok_akhir: 110,
        keterangan: 'Penambahan stok bulanan',
      },
      {
        komoditi: 'Beras Premium Slyp Super',
        divisi: 'Komersil',
        stok_awal: 40,
        stok_masuk: 20,
        stok_keluar: 0,
        stok_akhir: 60,
        keterangan: 'Penambahan stok dari hasil GPM Kereng Bangkirai',
      },
      {
        komoditi: 'Gula Manis Kita',
        divisi: 'Komersil',
        stok_awal: 50,
        stok_masuk: 0,
        stok_keluar: 10,
        stok_akhir: 40,
        keterangan: 'Stok dikurang karena dipakai untuk paketan',
      },
      {
        komoditi: 'Beras Medium SPHP Thailand',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 80,
        stok_masuk: 5,
        stok_keluar: 0,
        stok_akhir: 85,
        keterangan: 'Penambahan stok dari hasil GPM',
      },
      {
        komoditi: 'Beras Medium SPHP Thailand',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 85,
        stok_masuk: 0,
        stok_keluar: 5,
        stok_akhir: 80,
        keterangan: 'Pengurangan stok karena barang rusak',
      },
      {
        komoditi: 'Beras Medium SPHP Vietnam',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 100,
        stok_masuk: 0,
        stok_keluar: 10,
        stok_akhir: 90,
        keterangan: 'Stok dikurang karena diambil pak Wanto',
      },
    ],
  },
];
