export const salesReport = [
  {
    period: 'harian',
    data: [
      {
        komoditi: 'Beras Medium SPHP Thailand',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 80,
        stok_masuk: 5,
        stok_keluar: 0,
        stok_terjual: 15,
        hasil_penjualan: 1500000,
        stok_akhir: 70,
      },
      {
        komoditi: 'Beras Medium SPHP Vietnam',
        divisi: 'Komersil',
        stok_awal: 70,
        stok_masuk: 10,
        stok_keluar: 5,
        stok_terjual: 20,
        hasil_penjualan: 2000000,
        stok_akhir: 55,
      },
      {
        komoditi: 'Beras Premium Slyp Super',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 60,
        stok_masuk: 20,
        stok_keluar: 0,
        stok_terjual: 25,
        hasil_penjualan: 2500000,
        stok_akhir: 55,
      },
      {
        komoditi: 'Beras Premium Setra Ramos',
        divisi: 'Komersil',
        stok_awal: 90,
        stok_masuk: 30,
        stok_keluar: 0,
        stok_terjual: 40,
        hasil_penjualan: 4000000,
        stok_akhir: 80,
      },
      {
        komoditi: 'Beras Siam Kahayan',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 50,
        stok_masuk: 15,
        stok_keluar: 5,
        stok_terjual: 10,
        hasil_penjualan: 1000000,
        stok_akhir: 50,
      },
      {
        komoditi: 'Minyak Goreng Kita',
        divisi: 'Komersil',
        stok_awal: 100,
        stok_masuk: 20,
        stok_keluar: 10,
        stok_terjual: 25,
        hasil_penjualan: 2500000,
        stok_akhir: 85,
      },
      {
        komoditi: 'Bawang Putih',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 80,
        stok_masuk: 30,
        stok_keluar: 0,
        stok_terjual: 35,
        hasil_penjualan: 3500000,
        stok_akhir: 75,
      },
      {
        komoditi: 'Bawang Merah',
        divisi: 'Komersil',
        stok_awal: 120,
        stok_masuk: 10,
        stok_keluar: 5,
        stok_terjual: 30,
        hasil_penjualan: 3000000,
        stok_akhir: 95,
      },
      {
        komoditi: 'Beras Burung Tingang',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 70,
        stok_masuk: 25,
        stok_keluar: 0,
        stok_terjual: 20,
        hasil_penjualan: 2000000,
        stok_akhir: 75,
      },
    ],
  },
  {
    period: 'mingguan',
    data: [
      {
        komoditi: 'Beras Medium SPHP Thailand',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 560,
        stok_masuk: 35,
        stok_keluar: 0,
        stok_terjual: 105,
        hasil_penjualan: 10500000,
        stok_akhir: 490,
      },
      {
        komoditi: 'Beras Medium SPHP Vietnam',
        divisi: 'Komersil',
        stok_awal: 490,
        stok_masuk: 70,
        stok_keluar: 35,
        stok_terjual: 140,
        hasil_penjualan: 14000000,
        stok_akhir: 385,
      },
      {
        komoditi: 'Beras Premium Slyp Super',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 420,
        stok_masuk: 140,
        stok_keluar: 0,
        stok_terjual: 175,
        hasil_penjualan: 17500000,
        stok_akhir: 385,
      },
      {
        komoditi: 'Beras Premium Setra Ramos',
        divisi: 'Komersil',
        stok_awal: 630,
        stok_masuk: 210,
        stok_keluar: 0,
        stok_terjual: 280,
        hasil_penjualan: 28000000,
        stok_akhir: 560,
      },
      {
        komoditi: 'Beras Siam Kahayan',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 350,
        stok_masuk: 105,
        stok_keluar: 35,
        stok_terjual: 70,
        hasil_penjualan: 7000000,
        stok_akhir: 350,
      },
      {
        komoditi: 'Minyak Goreng Kita',
        divisi: 'Komersil',
        stok_awal: 700,
        stok_masuk: 140,
        stok_keluar: 70,
        stok_terjual: 175,
        hasil_penjualan: 17500000,
        stok_akhir: 595,
      },
      {
        komoditi: 'Bawang Putih',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 560,
        stok_masuk: 210,
        stok_keluar: 0,
        stok_terjual: 245,
        hasil_penjualan: 24500000,
        stok_akhir: 525,
      },
      {
        komoditi: 'Bawang Merah',
        divisi: 'Komersil',
        stok_awal: 840,
        stok_masuk: 70,
        stok_keluar: 35,
        stok_terjual: 210,
        hasil_penjualan: 21000000,
        stok_akhir: 665,
      },
      {
        komoditi: 'Beras Burung Tingang',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 490,
        stok_masuk: 175,
        stok_keluar: 0,
        stok_terjual: 140,
        hasil_penjualan: 14000000,
        stok_akhir: 525,
      },
    ],
  },
  {
    period: 'bulanan',
    data: [
      {
        komoditi: 'Beras Medium SPHP Thailand',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 2240,
        stok_masuk: 140,
        stok_keluar: 0,
        stok_terjual: 420,
        hasil_penjualan: 42000000,
        stok_akhir: 1960,
      },
      {
        komoditi: 'Beras Medium SPHP Vietnam',
        divisi: 'Komersil',
        stok_awal: 1960,
        stok_masuk: 280,
        stok_keluar: 140,
        stok_terjual: 560,
        hasil_penjualan: 56000000,
        stok_akhir: 1540,
      },
      {
        komoditi: 'Beras Premium Slyp Super',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 1680,
        stok_masuk: 560,
        stok_keluar: 0,
        stok_terjual: 700,
        hasil_penjualan: 70000000,
        stok_akhir: 1540,
      },
      {
        komoditi: 'Beras Premium Setra Ramos',
        divisi: 'Komersil',
        stok_awal: 2520,
        stok_masuk: 840,
        stok_keluar: 0,
        stok_terjual: 1120,
        hasil_penjualan: 112000000,
        stok_akhir: 1960,
      },
      {
        komoditi: 'Beras Siam Kahayan',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 1400,
        stok_masuk: 420,
        stok_keluar: 140,
        stok_terjual: 280,
        hasil_penjualan: 28000000,
        stok_akhir: 1400,
      },
      {
        komoditi: 'Minyak Goreng Kita',
        divisi: 'Komersil',
        stok_awal: 2800,
        stok_masuk: 560,
        stok_keluar: 280,
        stok_terjual: 700,
        hasil_penjualan: 70000000,
        stok_akhir: 2380,
      },
      {
        komoditi: 'Bawang Putih',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 2240,
        stok_masuk: 840,
        stok_keluar: 0,
        stok_terjual: 980,
        hasil_penjualan: 98000000,
        stok_akhir: 2100,
      },
      {
        komoditi: 'Bawang Merah',
        divisi: 'Komersil',
        stok_awal: 3360,
        stok_masuk: 280,
        stok_keluar: 140,
        stok_terjual: 840,
        hasil_penjualan: 84000000,
        stok_akhir: 2660,
      },
      {
        komoditi: 'Beras Burung Tingang',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 1960,
        stok_masuk: 700,
        stok_keluar: 0,
        stok_terjual: 560,
        hasil_penjualan: 56000000,
        stok_akhir: 2100,
      },
    ],
  },
  {
    period: 'tahunan',
    data: [
      {
        komoditi: 'Beras Medium SPHP Thailand',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 26880,
        stok_masuk: 1680,
        stok_keluar: 0,
        stok_terjual: 5040,
        hasil_penjualan: 504000000,
        stok_akhir: 21840,
      },
      {
        komoditi: 'Beras Medium SPHP Vietnam',
        divisi: 'Komersil',
        stok_awal: 23520,
        stok_masuk: 3360,
        stok_keluar: 1680,
        stok_terjual: 6720,
        hasil_penjualan: 672000000,
        stok_akhir: 18480,
      },
      {
        komoditi: 'Beras Premium Slyp Super',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 20160,
        stok_masuk: 6720,
        stok_keluar: 0,
        stok_terjual: 8400,
        hasil_penjualan: 840000000,
        stok_akhir: 18480,
      },
      {
        komoditi: 'Beras Premium Setra Ramos',
        divisi: 'Komersil',
        stok_awal: 30240,
        stok_masuk: 10080,
        stok_keluar: 0,
        stok_terjual: 13440,
        hasil_penjualan: 1344000000,
        stok_akhir: 26880,
      },
      {
        komoditi: 'Beras Siam Kahayan',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 16800,
        stok_masuk: 5040,
        stok_keluar: 1680,
        stok_terjual: 3360,
        hasil_penjualan: 336000000,
        stok_akhir: 16800,
      },
      {
        komoditi: 'Minyak Goreng Kita',
        divisi: 'Komersil',
        stok_awal: 33600,
        stok_masuk: 6720,
        stok_keluar: 3360,
        stok_terjual: 8400,
        hasil_penjualan: 840000000,
        stok_akhir: 30240,
      },
      {
        komoditi: 'Bawang Putih',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 26880,
        stok_masuk: 10080,
        stok_keluar: 0,
        stok_terjual: 11760,
        hasil_penjualan: 1176000000,
        stok_akhir: 25200,
      },
      {
        komoditi: 'Bawang Merah',
        divisi: 'Komersil',
        stok_awal: 40320,
        stok_masuk: 3360,
        stok_keluar: 1680,
        stok_terjual: 10080,
        hasil_penjualan: 1008000000,
        stok_akhir: 31920,
      },
      {
        komoditi: 'Beras Burung Tingang',
        divisi: 'Supply Chain dan Pelayanan Publik',
        stok_awal: 23520,
        stok_masuk: 8400,
        stok_keluar: 0,
        stok_terjual: 6720,
        hasil_penjualan: 672000000,
        stok_akhir: 25200,
      },
    ],
  },
];
